language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  
matrix:
  allow_failures:
    - php: hhvm
    - php: 5.6
  
env:
  - DB=mysql

before_script:
#  - "sudo apt-get update | yes && sudo apt-get upgrade | yes"
  - "chmod +x ./travis/makedb.sh"
  - "chmod +x ./travis/testsite.sh"  
  - "mysql -e 'CREATE DATABASE zarthus;'"
  
script:
  - "./travis/makedb.sh"
  - "mv travis/config.default.php zarth.us/includes/php/config.php"
  - "mv travis/zarth.us.php zarth.us/zarth.us.php"
  - "chmod +x zarth.us/zarth.us.php"
  - "php zarth.us/zarth.us.php"

notifications:
  email: true
  irc: "irc.esper.net#zarthus"