language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  
matrix:
  allow_failures:
    - php: hhvm
    - php: 5.6
  
env:
  - DB=mysql

before_script:
#  - "sudo apt-get update && sudo apt-get upgrade"
  - "chmod +x travis/makedb.sh"
  - "chmod +x travis/testsite.sh"  
  
script:
  - "./travis/makedb.sh"
  - "./travis/testsite.sh"
  
notifications:
  email: true
  irc: "irc.esper.net#zarthus"